Whitelist vercel deploy script
iFixit/govinor pull request #7
Opened 2024-09-20 22:00 UTC by masonmcelvain

The ifixit-nextjs-dev PR deploy failed a few times in https://github.com/iFixit/ifixit/pull/55534, and it turns out we don't deploy strapi when there are changes to the vercel deploy script. This change deploys strapi in that case, and also clarifies the webhook response message to make debugging a little easier.

CC @jarstelfox

2024-09-20 22:01 UTC, jarstelfox approved these changes
CR 🌵

2024-09-21 19:21 UTC, deltuh-vee commented
@masonmcelvain 
Does this pull need QA?

2024-09-23 09:03 UTC, dhmacs requested changes
I spotted a Typescript issue. Let me know if you want me to complete this pull and ship it (we're still deploying manually here).

As a side note, remember we also have the ability to boot any branch whenever our automatic rules don't cover a specific scenario where we'd like to have a Govinor instance:

https://govinor.com/repositories/a2a4ff62-d9f1-4066-a2e9-5ed9a36f751d/branches/new

2024-09-23 19:18 UTC, danielbeardsley commented on app/routes/github.webhook/pull-request-webhook.ts
> +      });
There are about 20 actions... hmm... seems like we're missing possibly an important one `reopened`:
![image](https://github.com/user-attachments/assets/bcfd8784-d381-4ba4-b313-001c2e65e48a)

2024-10-03 21:21 UTC, masonmcelvain commented
dev_block 👍🏻

2024-10-30 20:42 UTC, masonmcelvain commented
I am not interested in merging this since we have a way to boot any branch.

It would be nice if that link to boot a branch was available somewhere in the Strapi UI, I was not aware that feature was available.

2024-10-30 20:42 UTC, closed without merging

2024-10-30 20:51 UTC, dhmacs commented
@masonmcelvain it's in the repo page: https://govinor.com/repositories/a2a4ff62-d9f1-4066-a2e9-5ed9a36f751d

<img width="749" alt="Screenshot 2024-10-30 at 21 50 30" src="https://github.com/user-attachments/assets/0b087c13-b170-45da-9e1f-4f0166224a55">

I can make it more visible, since maybe it's not obvious that it's a link

2024-10-30 21:03 UTC, masonmcelvain commented
Ah I see thanks! I didn't notice that button, I thought it was text 😓